export const itensBoardRegister = [
  'Cód. Boletim',
  'Matrícula Condutor',
  'Nome do Condutor',
  'Centro de Resultado',
  'Data',
  'Código Veículo',
  'Placa',
  'Km Inicial',
  'Km Final',
  'Km Rodado',
  'Itinerário Origem',
  'Itinerário Destino',
  'Houve Abastecimento',
  'Quantidade Abastecida',
  'R$ Unit',
  'R$ Total',
];

export const itensFunctionary = [
  'Matrícula',
  'Nome',
  'CPF',
  'E-mail',
  'Data de Admissão',
  'Função',
  'Telefone',
  'Número da CNH',
  'Categoria da CNH',
  'Validade da CNH',
  'Status',
  'Rua',
  'Numero',
  'Bairro',
  'Cidade',
  'Estado',
  'CEP',
  'Complemento',
];
